### ISSUE TITLE
test_make_features failing

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#17]
It looks like all the tests pass on the new repo except for test_make_features which is failing with errors like this:
```
Traceback (most recent call last):
  File "make_features_test.py", line 58, in test_make_features
    querydict = create_insert_query(alert)
  File "/var/lib/jenkins/workspace/asai_bugfix_tests/pipeline/filter/insert_query.py", line 20, in create_insert_query
    diaObject = alert['diaObject']
KeyError: 'diaObject'
```

This looks like an actual problem with the code being tested and not just with the test. Please fix in the bugfix/tests branch where I've fixed the other testing problems so we can verify it works.

**Comment by gpfrancis** [comment]
I think this is now fixed. Please reopen if that's not the case.
