### ISSUE TITLE
Locking issue with sherlock cache

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/lasair-lsst#61]
('ZTF20abckvit','AGN',%s) ON DUPLICATE KEY UPDATE class=VALUES(class), crossmatch=VALUES(crossmatch)
Traceback (most recent call last):
  File "/wrapper.py", line 372, in <module>
    run(conf, log)
  File "/wrapper.py", line 305, in run
    n = consume(conf, log, alerts, consumer)
  File "/wrapper.py", line 82, in consume
    n_classified = classify(conf, log, alerts)
  File "/wrapper.py", line 235, in classify
    cursor.execute(query, crossmatches)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
  File "/usr/local/lib/python3.8/dist-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/local/lib/python3.8/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1213, 'Deadlock found when trying to get lock; try restarting transaction')

**Comment by tms-epcc** [comment]
14/JUL/21
- @gpfrancis explained this is currently blocked by a Sherlock issue
